"use strict";
process.env.NODE_TLS_REJECT_UNAUTHORIZED="0";
process.on("warning",()=>{});

import tls from "node:tls";
import http2 from "node:http2";
import dns from "node:dns";
import {readFileSync,watch} from "node:fs";
import os from "node:os";

const TOKEN="";
const PASS="";
const GUILD="";
const CHAN="";
const ua="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36";
const sp="eyJvcyI6IldpbmRvd3MiLCJicm93c2VyIjoiQ2hyb21lIiwiZGV2aWNlIjoiIiwic3lzdGVtX2xvY2FsZSI6InRyIiwiYnJvd3Nlcl91c2VyX2FnZW50IjoiTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEzOC4wLjAuMCBTYWZhcmkvNTM3LjM2IiwiYnJvd3Nlcl92ZXJzaW9uIjoiMTM4LjAuMC4wIiwib3NfdmVyc2lvbiI6IjEwIiwicmVmZXJyZXIiOiIiLCJyZWZlcnJpbmdfZG9tYWluIjoiIiwicmVmZXJyZXJfY3VycmVudCI6IiIsInJlZmVycmluZ19kb21haW5fY3VycmVudCI6IiIsInJlbGVhc2VfY2hhbm5lbCI6InN0YWJsZSIsImNsaWVudF9idWlsZF9udW1iZXIiOjI2MDAwMCwiY2xpZW50X2V2ZW50X3NvdXJjZSI6bnVsbH0=";

const H=4,H2=4,GN=3,BUF=1<<21,HWM=1<<20,ROT=180_000,RING=1024;
const CF_IP="162.159.137.232";
const API_VERS=[6,7,8,9,10];

const pOP=b('"op":'),pSQ=b('"s":'),pRD=b('"READY"');
const pGU=b("GUILD_UPDATE");
const pDT=b('"d":true'),pDI=b('"d":{"id":"'),pVC=b('"vanity_url_code"');
const CRLF=Buffer.from("\r\n\r\n");
const FATAL=new Uint8Array(16384);[4004,4010,4011,4012,4013,4014].forEach(c=>{FATAL[c]=1;});
const HEX=new Uint8Array(256);
for(let i=0;i<10;i++)HEX[0x30+i]=i;
for(let i=0;i<6;i++){HEX[0x41+i]=10+i;HEX[0x61+i]=10+i;}
const RLD=Buffer.from("x-ratelimit-reset-after:");
const PING=Buffer.from("GET /api/v10/gateway HTTP/1.1\r\nHost: discord.com\r\nConnection: keep-alive\r\n\r\n");

const MFA_PATCH_H=Buffer.from("PATCH /api/v10/guilds/"+GUILD+"/vanity-url HTTP/1.1\r\nHost: discord.com\r\nAuthorization: "+TOKEN+"\r\nUser-Agent: "+ua+"\r\nX-Super-Properties: "+sp+"\r\nContent-Type: application/json\r\nConnection: keep-alive\r\nContent-Length: ");
const MFA_FINISH_H=Buffer.from("POST /api/v10/mfa/finish HTTP/1.1\r\nHost: discord.com\r\nAuthorization: "+TOKEN+"\r\nUser-Agent: "+ua+"\r\nX-Super-Properties: "+sp+"\r\nContent-Type: application/json\r\nConnection: keep-alive\r\nContent-Length: ");
const MFA_EMPTY=Buffer.from('{"code":""}');

const TOPT={port:443,servername:"discord.com",rejectUnauthorized:false,ALPNProtocols:["http/1.1"],highWaterMark:HWM,minVersion:"TLSv1.3",maxVersion:"TLSv1.3",ciphers:"TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256",ecdhCurve:"X25519"};
const H2OPT={maxSessionMemory:100000000,settings:{enablePush:false,initialWindowSize:16965000,maxConcurrentStreams:100,maxFrameSize:13000,headerTableSize:60000,enableConnectProtocol:false},paddingStrategy:http2.constants.PADDING_STRATEGY_NONE};

const sess=new Map(),h2sess=new Map();
const ET=new Uint8Array(128);ET[92]=1;ET[34]=2;ET[10]=3;ET[13]=4;
const EK=["","\\\\",'\\"',"\\n","\\r"];

const _=()=>{};
const log=s=>process.stdout.write(s+"\n");
function b(s){return Buffer.from(s);}
function esc(s){let o="",p=0;for(let i=0,l=s.length;i<l;i++){const k=s.charCodeAt(i);if(k<128){const t=ET[k];if(t){o+=s.substring(p,i)+EK[t];p=i+1;}}}return p===0?s:o+s.substring(p);}

let mfaTok="",mfaBusy=false,mfaNext=0,mfaSock=null,idNext=0;
const van=new Map(),active=new Set();
let pkts=new Map(),h2pkts=new Map(),tmg=new Map();
const RM=RING-1,ring=new Array(RING);
let rB=0,rS=0,rBusy=false,rTs=0,rGen=0;
let pH=null,mH=null,h2pH=null;
const pool=new Array(H),h2Pool=new Array(H2),msgPool=new Array(GN),warm=new Array(H);

function find(buf,len,pat,pl){if(len<pl)return -1;const f=pat[0],e=len-pl;let i=0;nx:while(i<=e){if(buf[i]!==f){i++;continue;}for(let j=1;j<pl;j++)if(buf[i+j]!==pat[j]){i++;continue nx;}return i;}return -1;}
function rlParse(buf,hs){const dl=RLD.length;for(let i=0,s=hs-dl;i<s;i++){let ok=true;for(let j=0;j<dl;j++){const c=buf[i+j],p=RLD[j];if(c!==p&&!(c>=65&&c<=90&&c+32===p)){ok=false;break;}}if(!ok)continue;let c=i+dl;while(c<hs&&buf[c]===32)c++;let v=0,dot=false,sc=1;while(c<hs&&buf[c]!==13){const r=buf[c];if(r>=48&&r<=57){if(dot){sc*=10;v+=(r-48)/sc;}else v=v*10+(r-48);}else if(r===46)dot=true;else break;c++;}return v>0?v:-1;}return -1;}
function retryMs(s,def){const i=s.indexOf('"retry_after"');if(i===-1)return def;let c=i+14,v=0,dot=false,sc=1;const l=s.length;while(c<l&&(s.charCodeAt(c)===32||s.charCodeAt(c)===58))c++;while(c<l){const r=s.charCodeAt(c);if(r>=48&&r<=57){if(dot){sc*=10;v+=(r-48)/sc;}else v=v*10+(r-48);}else if(r===46)dot=true;else break;c++;}return v>0?Math.max(0,(v*1000)|0):def;}
function mkParser(){let buf=Buffer.allocUnsafe(BUF),ofs=0,hs=-1,cl=-1,chunked=false,st=0,rl=-1;function feed(chunk,cb){if(ofs+chunk.length>buf.length){const nb=Buffer.allocUnsafe(Math.max((ofs+chunk.length)<<1,BUF));buf.copy(nb,0,0,ofs);buf=nb;}chunk.copy(buf,ofs);ofs+=chunk.length;parse(cb);}function parse(cb){for(;;){if(hs<0){for(let i=0,s=ofs-3;i<s;i++)if(buf[i]===13&&buf[i+1]===10&&buf[i+2]===13&&buf[i+3]===10){hs=i;break;}if(hs<0)return;st=(hs>12&&buf[0]===72)?(buf[9]-48)*100+(buf[10]-48)*10+(buf[11]-48):0;if(st<100||st>599)st=0;rl=rlParse(buf,hs);chunked=false;for(let i=0,s=hs-6;i<s;i++)if(buf[i]===99&&buf[i+1]===104&&buf[i+2]===117&&buf[i+3]===110&&buf[i+4]===107&&buf[i+5]===101&&buf[i+6]===100){chunked=true;break;}if(!chunked){cl=-1;for(let i=0,s=hs-15;i<s;i++){if((buf[i]===67||buf[i]===99)&&buf[i+7]===45&&(buf[i+8]===76||buf[i+8]===108)){let j=i+15;while(j<hs&&buf[j]===32)j++;let v=0;while(j<hs&&buf[j]>=48&&buf[j]<=57){v=v*10+(buf[j]-48);j++;}cl=v;break;}}if(cl<0)cl=(st===204||st===304||(st>0&&st<200))?0:-1;}}const bs=hs+4;if(chunked){let pos=bs,fb=-1,fl=0,one=true,parts=null;for(;;){let le=-1;for(let i=pos,s=ofs-1;i<s;i++)if(buf[i]===13&&buf[i+1]===10){le=i;break;}if(le<0)return;let cs=0;for(let i=pos;i<le;i++)cs=(cs<<4)|HEX[buf[i]];const ds=le+2,de=ds+cs;if(ofs<de+2)return;if(cs===0){let te=-1;for(let i=le,s=ofs-3;i<s;i++)if(buf[i]===13&&buf[i+1]===10&&buf[i+2]===13&&buf[i+3]===10){te=i;break;}if(te<0)return;const rem=ofs-(te+4);if(rem>0)buf.copy(buf,0,te+4,ofs);ofs=rem;hs=-1;cl=-1;chunked=false;cb(one&&fb>=0?buf.toString("utf8",fb,fb+fl):(parts?parts.join(""):""),st,rl);break;}if(one&&fb<0){fb=ds;fl=cs;}else if(one){one=false;parts=[buf.toString("utf8",fb,fb+fl),buf.toString("utf8",ds,de)];}else parts.push(buf.toString("utf8",ds,de));pos=de+2;}}else{if(cl<0||ofs-bs<cl)return;const g=cl>0?buf.toString("utf8",bs,bs+cl):"";const tk=bs+cl,rem=ofs-tk;if(rem>0)buf.copy(buf,0,tk,ofs);ofs=rem;hs=-1;cl=-1;chunked=false;cb(g,st,rl);}}}function reset(){ofs=0;hs=-1;cl=-1;chunked=false;st=0;rl=-1;}return{feed,reset};}

function conn(iIdx){const p=mkParser();const QM=63,QV=new Array(64),QC=new Array(64);let qB=0,qS=0,sok=null,busy=false,cb=null,cv=null,gen=0,at=0;function connect(){if(sok&&!sok.destroyed)return;const n=++gen;p.reset();sok=tls.connect({...TOPT,host:CF_IP,session:sess.get(CF_IP)||null});sok.setNoDelay(true);sok.setKeepAlive(true,2000);sok.setTimeout(0);if(sok.socket){sok.socket.setNoDelay(true);sok.socket.setKeepAlive(true,2000);}sok.once("session",s=>sess.set(CF_IP,s));sok.once("secureConnect",()=>{at=Date.now();});sok.on("data",c=>{if(n!==gen)return;p.feed(c,done);});sok.on("error",_);sok.on("close",()=>{if(n!==gen)return;const pCb=cb,pV=cv;busy=false;cb=null;cv=null;at=0;qB=qS=0;connect();if(pCb&&pV)send(pV,pCb);});}function done(g,s,r){busy=false;cv=null;const c2=cb;cb=null;if(c2)c2(g,s,r);if(qB!==qS){const i=qB&QM,v=QV[i],x=QC[i];QV[i]=QC[i]=null;qB++;send(v,x);}}function send(data,cb2){if(!sok||sok.destroyed){const i=qS&QM;QV[i]=data;QC[i]=cb2;qS++;connect();return;}if(busy){const i=qS&QM;QV[i]=data;QC[i]=cb2;qS++;return;}busy=true;cb=cb2;cv=data;sok.cork();sok.write(data);sok.uncork();}send.kill=()=>{gen++;at=0;if(sok&&!sok.destroyed)sok.destroy();sok=null;busy=false;cb=null;qB=qS=0;};send.age=()=>at>0?Date.now()-at:0;connect();return send;}

function mkH2Session(iIdx){const session=http2.connect("https://discord.com",{...H2OPT,createConnection:()=>{const s=tls.connect({host:CF_IP,port:443,servername:"discord.com",rejectUnauthorized:false,ALPNProtocols:["h2"],minVersion:"TLSv1.3",maxVersion:"TLSv1.3",ciphers:"TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256",ecdhCurve:"X25519",highWaterMark:HWM,session:h2sess.get(CF_IP)||null});s.setNoDelay(true);s.setKeepAlive(true,2000);if(s.socket){s.socket.setNoDelay(true);s.socket.setKeepAlive(true,2000);}s.once("session",sv=>h2sess.set(CF_IP,sv));return s;}});session._idx=iIdx;session.on("error",()=>{if(h2Pool[iIdx]===session)h2Pool[iIdx]=mkH2Session(iIdx);});session.on("close",()=>{if(h2Pool[iIdx]===session)h2Pool[iIdx]=mkH2Session(iIdx);});return session;}

function warmConn(iIdx){const p=mkParser();let ready=false,fired=false,cb=null;const sok=tls.connect({...TOPT,host:CF_IP,session:sess.get(CF_IP)||null});sok.setNoDelay(true);sok.setKeepAlive(true,2000);if(sok.socket){sok.socket.setNoDelay(true);sok.socket.setKeepAlive(true,2000);}sok.once("session",s=>sess.set(CF_IP,s));sok.once("secureConnect",()=>{ready=true;});sok.on("data",c=>p.feed(c,done));sok.on("error",_);sok.on("close",()=>{ready=false;});function done(g,s,r){const c2=cb;cb=null;if(c2)c2(g,s,r);if(!sok.destroyed)sok.destroy();}function fire(data,cb2){if(fired)return;fired=true;cb=cb2;if(ready){sok.cork();sok.write(data);sok.uncork();}else sok.once("secureConnect",()=>{sok.cork();sok.write(data);sok.uncork();});}fire.ready=()=>ready;fire.kill=()=>{if(!sok.destroyed)sok.destroy();};return fire;}

function renewWarm(i){if(warm[i])warm[i].kill();warm[i]=warmConn(i);}
for(let i=0;i<H;i++)renewWarm(i);
setInterval(()=>{for(let i=0;i<H;i++)if(!warm[i].ready())renewWarm(i);},5_000);

function buildHdrs(){pH=mfaTok?Buffer.from("PATCH /api/v10/guilds/"+GUILD+"/vanity-url HTTP/1.1\r\nHost: discord.com\r\nAuthorization: "+TOKEN+"\r\nUser-Agent: "+ua+"\r\nX-Super-Properties: "+sp+"\r\nContent-Type: application/json\r\nX-Discord-MFA-Authorization: "+mfaTok+"\r\nConnection: keep-alive\r\nContent-Length: "):null;h2pH=mfaTok?{":method":"PATCH",":path":"/api/v10/guilds/"+GUILD+"/vanity-url",":authority":"discord.com",":scheme":"https","authorization":TOKEN,"content-type":"application/json","user-agent":ua,"x-super-properties":sp,"x-discord-mfa-authorization":mfaTok}:null;mH=CHAN?Buffer.from("POST /api/v10/channels/"+CHAN+"/messages HTTP/1.1\r\nHost: discord.com\r\nAuthorization: "+TOKEN+"\r\nUser-Agent: "+ua+"\r\nContent-Type: application/json\r\nConnection: keep-alive\r\nContent-Length: "):null;}

function buildPkt(code){const g=Buffer.from('{"code":"'+code+'"}');const tlsAll=[];for(const v of API_VERS){const h=Buffer.from("PATCH /api/v"+v+"/guilds/"+GUILD+"/vanity-url HTTP/1.1\r\nHost: discord.com\r\nAuthorization: "+TOKEN+"\r\nUser-Agent: "+ua+"\r\nX-Super-Properties: "+sp+"\r\nContent-Type: application/json\r\nX-Discord-MFA-Authorization: "+mfaTok+"\r\nConnection: keep-alive\r\nContent-Length: "+g.length);const p=Buffer.allocUnsafe(h.length+CRLF.length+g.length);let o=0;o+=h.copy(p,o);o+=CRLF.copy(p,o);g.copy(p,o);tlsAll.push(p);}pkts.set(code,Buffer.concat(tlsAll));if(h2pH){const h2All=[];for(const v of API_VERS){h2All.push({headers:{":method":"PATCH",":path":"/api/v"+v+"/guilds/"+GUILD+"/vanity-url",":authority":"discord.com",":scheme":"https","authorization":TOKEN,"content-type":"application/json","user-agent":ua,"x-super-properties":sp,"x-discord-mfa-authorization":mfaTok,"content-length":String(g.length)},payload:g.toString()});}h2pkts.set(code,h2All);}}

function rebuildPkts(){const n=new Map(),n2=new Map();for(const code of van.values()){const g=Buffer.from('{"code":"'+code+'"}');const tlsAll=[];for(const v of API_VERS){const h=Buffer.from("PATCH /api/v"+v+"/guilds/"+GUILD+"/vanity-url HTTP/1.1\r\nHost: discord.com\r\nAuthorization: "+TOKEN+"\r\nUser-Agent: "+ua+"\r\nX-Super-Properties: "+sp+"\r\nContent-Type: application/json\r\nX-Discord-MFA-Authorization: "+mfaTok+"\r\nConnection: keep-alive\r\nContent-Length: "+g.length);const p=Buffer.allocUnsafe(h.length+CRLF.length+g.length);let o=0;o+=h.copy(p,o);o+=CRLF.copy(p,o);g.copy(p,o);tlsAll.push(p);}n.set(code,Buffer.concat(tlsAll));if(h2pH){const h2All=[];for(const v of API_VERS){h2All.push({headers:{":method":"PATCH",":path":"/api/v"+v+"/guilds/"+GUILD+"/vanity-url",":authority":"discord.com",":scheme":"https","authorization":TOKEN,"content-type":"application/json","user-agent":ua,"x-super-properties":sp,"x-discord-mfa-authorization":mfaTok,"content-length":String(g.length)},payload:g.toString()});}n2.set(code,h2All);}}pkts=n;h2pkts=n2;}

function fireH2(code,pktList){for(let i=0;i<H2;i++){const s=h2Pool[i];if(!s||s.destroyed||s.closed)continue;for(const pkt of pktList){try{let st=0,data="";const req=s.request(pkt.headers);req.on("response",(hdrs)=>{st=hdrs[":status"]||0;});req.on("data",c=>{data+=c;});req.on("end",()=>{const v=pkt.headers[":path"].split("/")[2];if(st!==200&&st!==204)log("h2 v"+v+" "+code+" "+st+" "+data.substring(0,80));queue(code,data,st);});req.on("error",_);req.end(pkt.payload);}catch(_){}}}}

function snipe(code){if(active.has(code))return;active.add(code);const pkt=pkts.get(code),h2pkt=h2pkts.get(code);if(!pkt&&!h2pkt){active.delete(code);return;}let done=0;const total=H*2;const fin=()=>{if(++done>=total)active.delete(code);};if(pkt){for(let i=0;i<H;i++)fire(code,pkt,pool[i],fin);for(let i=0;i<H;i++){const w=warm[i];renewWarm(i);fire(code,pkt,w,fin);}}if(h2pkt)fireH2(code,h2pkt);}

function fire(code,pkt,c,fin){c(pkt,(body,st)=>{const s=String(body||"");if(s.length>200&&(s.charCodeAt(0)===60||s.includes("sentry")||s.includes("cf-ray"))){fin();return;}if(st!==200&&st!==204)log("tls "+code+" "+st+" "+s.substring(0,80));queue(code,s,st);fin();});}

function queue(code,body,st){if(!mH)return;if((rS-rB)>=RING){ring[rB&RM]=null;rB++;}let ic=body||(st===200?"ok":"(empty)");if(ic.length>1700)ic=ic.substring(0,1700)+"...";const mt="@everyone `"+code+"` "+st+"\n```json\n"+ic+"\n```";const yk=Buffer.from('{"content":"'+esc(mt)+'"}'),ul=Buffer.from(String(yk.length));const ist=Buffer.allocUnsafe(mH.length+ul.length+CRLF.length+yk.length);let o=0;o+=mH.copy(ist,o);o+=ul.copy(ist,o);o+=CRLF.copy(ist,o);yk.copy(ist,o);ring[rS&RM]=ist;rS++;flush();}

function flush(){if(rBusy||rB===rS)return;rBusy=true;rTs=Date.now();const j=++rGen;msgPool[rB%GN](ring[rB&RM],(body,st,rl)=>{if(j!==rGen)return;rBusy=false;if(st>=200&&st<300){ring[rB&RM]=null;rB++;}else if(st===429){const w=rl>0?(rl*1000)|0:retryMs(body||"",0);flush();return;}else{ring[rB&RM]=null;rB++;}if(rB!==rS)flush();});}
setInterval(()=>{if(rB!==rS&&rBusy&&Date.now()-rTs>8000){rGen++;rBusy=false;flush();}},2000);

function trackTime(gid){let a=tmg.get(gid);if(!a){a=[];tmg.set(gid,a);}a.push(Date.now());if(a.length>10)a.shift();}
function nextEta(gid){const a=tmg.get(gid);if(!a||a.length<2)return null;let t=0;for(let i=1;i<a.length;i++)t+=a[i]-a[i-1];return a[a.length-1]+t/(a.length-1);}
function predictNext(gid){const t=nextEta(gid);if(!t)return;const delta=(t-Date.now())|0;if(delta>0&&delta<90_000){log("predict "+gid+" "+delta+"ms");for(let i=0;i<H;i++)if(pool[i].age()>30_000){pool[i].kill();pool[i]=conn(i);}for(let i=0;i<H;i++)renewWarm(i);}}

function onGw(buf,len,ses){if(find(buf,len,pGU,12)!==-1){let gid,nv=null;const di=find(buf,len,pDI,11);if(di!==-1){let s=di+11;while(s<len&&buf[s]!==34)s++;gid=buf.toString("utf8",di+11,s);const vi=find(buf,len,pVC,17);if(vi!==-1){let vb=vi+18;if(vb<len&&buf[vb]===34){vb++;let ve=vb;while(ve<len&&buf[ve]!==34)ve++;if(ve>vb)nv=buf.toString("utf8",vb,ve);}}else{try{const p=JSON.parse(buf.toString());nv=p.d?.vanity_url_code||null;}catch{}}}else{let p;try{p=JSON.parse(buf.toString());}catch{return;}if(!p.d)return;gid=p.d.id;nv=p.d.vanity_url_code||null;}if(!gid)return;const old=van.get(gid);if(old&&old!==nv){trackTime(gid);snipe(old);if(nv){van.set(gid,nv);buildPkt(nv);}else van.delete(gid);predictNext(gid);}else if(!old&&nv){van.set(gid,nv);buildPkt(nv);}return;}if(find(buf,len,pRD,7)!==-1){let p;try{p=JSON.parse(buf.toString());}catch{return;}if(p.t!=="READY"||!p.d)return;if(ses){ses.sid=p.d.session_id||null;ses.url=p.d.resume_gateway_url||null;}van.clear();const nm=new Map(),nm2=new Map();const gs=p.d.guilds||[];for(let i=0,l=gs.length;i<l;i++){const g=gs[i];if(!g.vanity_url_code)continue;van.set(g.id,g.vanity_url_code);const code=g.vanity_url_code;const gv=Buffer.from('{"code":"'+code+'"}');const tlsAll=[];for(const v of API_VERS){const h=Buffer.from("PATCH /api/v"+v+"/guilds/"+GUILD+"/vanity-url HTTP/1.1\r\nHost: discord.com\r\nAuthorization: "+TOKEN+"\r\nUser-Agent: "+ua+"\r\nX-Super-Properties: "+sp+"\r\nContent-Type: application/json\r\nX-Discord-MFA-Authorization: "+mfaTok+"\r\nConnection: keep-alive\r\nContent-Length: "+gv.length);const pk=Buffer.allocUnsafe(h.length+CRLF.length+gv.length);let o=0;o+=h.copy(pk,o);o+=CRLF.copy(pk,o);gv.copy(pk,o);tlsAll.push(pk);}nm.set(code,Buffer.concat(tlsAll));if(h2pH){const h2All=[];for(const v of API_VERS){h2All.push({headers:{":method":"PATCH",":path":"/api/v"+v+"/guilds/"+GUILD+"/vanity-url",":authority":"discord.com",":scheme":"https","authorization":TOKEN,"content-type":"application/json","user-agent":ua,"x-super-properties":sp,"x-discord-mfa-authorization":mfaTok,"content-length":String(gv.length)},payload:'{"code":"'+code+'"}'});}nm2.set(code,h2All);}}pkts=nm;h2pkts=nm2;log("ready guilds="+gs.length);}}

function wsFrame(text){const d=Buffer.from(text,"utf8"),len=d.length;let h;if(len<126){h=Buffer.allocUnsafe(6);h[1]=0x80|len;}else if(len<65536){h=Buffer.allocUnsafe(8);h[1]=0xFE;h.writeUInt16BE(len,2);}else{h=Buffer.allocUnsafe(14);h[1]=0xFF;h.writeBigUInt64BE(BigInt(len),2);}h[0]=0x81;const m=Buffer.allocUnsafe(4);m[0]=(Math.random()*256)|0;m[1]=(Math.random()*256)|0;m[2]=(Math.random()*256)|0;m[3]=(Math.random()*256)|0;const off=h.length-4;m.copy(h,off);const md=Buffer.allocUnsafe(len);for(let i=0;i<len;i++)md[i]=d[i]^m[i&3];return Buffer.concat([h.slice(0,off),m,md]);}

function wsCon(url,onMsg,onClose){const mx=url.match(/^wss?:\/\/([^\/]+)(\/.*)?$/),host=mx[1],path=mx[2]||"/";const key=Buffer.allocUnsafe(16);for(let i=0;i<16;i++)key[i]=(Math.random()*256)|0;const hs="GET "+path+" HTTP/1.1\r\nHost: "+host+"\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Key: "+key.toString("base64")+"\r\nSec-WebSocket-Version: 13\r\nUser-Agent: "+ua+"\r\n\r\n";let sok,buf=Buffer.allocUnsafe(65536),bLen=0,closeCode=1000,gone=false;function finish(){if(gone)return;gone=true;onClose(closeCode);}function connect(){sok=tls.connect({host:CF_IP,port:443,servername:host,rejectUnauthorized:false,minVersion:"TLSv1.3",maxVersion:"TLSv1.3",ciphers:"TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256",ecdhCurve:"X25519",highWaterMark:HWM});sok.setNoDelay(true);sok.setKeepAlive(true,2000);if(sok.socket){sok.socket.setNoDelay(true);sok.socket.setKeepAlive(true,2000);}sok.once("secureConnect",()=>{sok.write(hs);sok.once("data",c=>{const sep=c.indexOf("\r\n\r\n");if(sep===-1||!c.slice(0,sep).includes("101")){sok.destroy();return;}bLen=0;sok.on("data",onFrame);onMsg(null,"open");const rest=c.slice(sep+4);if(rest.length>0)onFrame(rest);});});sok.on("error",_);sok.on("close",finish);}function onFrame(chunk){if(bLen+chunk.length>buf.length){const nb=Buffer.allocUnsafe(Math.max((bLen+chunk.length)<<1,65536));buf.copy(nb,0,0,bLen);buf=nb;}chunk.copy(buf,bLen);bLen+=chunk.length;for(;;){if(bLen<2)return;const fin=buf[0]&0x80,op=buf[0]&0x0F;let pl=buf[1]&0x7F,off=2;if(pl===126){if(bLen<4)return;pl=buf.readUInt16BE(2);off=4;}else if(pl===127){if(bLen<10)return;pl=Number(buf.readBigUInt64BE(2));off=10;}if(bLen<off+pl)return;const vd=buf.slice(off,off+pl);const rem=bLen-(off+pl);if(op===8){closeCode=vd.length>=2?vd.readUInt16BE(0):1000;if(rem>0)buf.copy(buf,0,off+pl,bLen);bLen=rem;sok.destroy();return;}if((op===1||op===2)&&fin)onMsg(vd,"message");if(rem>0)buf.copy(buf,0,off+pl,bLen);bLen=rem;if(op===9)send(Buffer.from([0x8A,0x80,0,0,0,0]));}}function send(d){if(sok&&!sok.destroyed){sok.cork();sok.write(d);sok.uncork();}}function close(code){closeCode=code||1000;if(sok&&!sok.destroyed)sok.destroy();}connect();return{send:s=>send(wsFrame(s)),close};}

function gateway(url){const ses={sid:null,url:null};let backoff=300;const ident='{"op":2,"d":{"token":"'+TOKEN+'","intents":1,"properties":{"os":"linux","browser":"chrome","device":""},"compress":false}}';function connect(wsUrl,resume){let hb=null,ack=true,miss=0,seq=null,hbp='{"op":1,"d":null}';const ws=wsCon(wsUrl,(msg,type)=>{if(type==="open"){backoff=300;log("connected");return;}if(!msg)return;const len=msg.length;const si=find(msg,len,pSQ,4);if(si!==-1){let c=si+4;while(c<len&&msg[c]===32)c++;if(msg[c]>=48&&msg[c]<=57){let s=0;while(c<len&&msg[c]>=48&&msg[c]<=57){s=s*10+(msg[c]-48);c++;}if(s!==seq){seq=s;hbp='{"op":1,"d":'+s+'}';}}}const oi=find(msg,len,pOP,5);if(oi<0)return;let op=oi+5;while(op<len&&msg[op]===32)op++;const a=msg[op],a2=msg[op+1];if(a===49&&a2===49){ack=true;miss=0;return;}if(a===48){onGw(msg,len,ses);return;}if(a===49&&a2===48){if(hb)clearInterval(hb);ack=true;miss=0;const t=msg.toString("utf8");let iv=0,hi=t.indexOf("heartbeat_interval");if(hi!==-1){let c=hi+20;while(c<t.length&&(t.charCodeAt(c)===32||t.charCodeAt(c)===58))c++;while(c<t.length&&t.charCodeAt(c)>=48&&t.charCodeAt(c)<=57){iv=iv*10+(t.charCodeAt(c)-48);c++;}}if(iv>0){if(ws)ws.send(hbp);hb=setInterval(()=>{if(!ack){miss++;if(miss>=2){log("hb timeout");ws.close(4000);return;}}else miss=0;ack=false;if(ws)ws.send(hbp);},(iv*0.9)|0);}if(resume&&ses.sid){ws.send('{"op":6,"d":{"token":"'+TOKEN+'","session_id":"'+ses.sid+'","seq":'+(seq!=null?seq:"null")+'}}');}else{const now=Date.now(),d=Math.max(0,idNext-now);idNext=Math.max(now,idNext)+5500;if(d>0)return;ws.send(ident);}return;}if(a===49&&(a2<48||a2>57)){ack=false;if(ws)ws.send(hbp);return;}if(a===55){backoff=300;ws.close(4000);return;}if(a===57){const ok=find(msg,len,pDT,8)!==-1;if(!ok){ses.sid=null;ses.url=null;}ws.close(4000);}},code=>{if(hb){clearInterval(hb);hb=null;}if(FATAL[code]){log("fatal "+code);return;}if(code===4007||code===4000){ses.sid=null;ses.url=null;}const resume2=!!ses.sid&&code!==4007&&code!==4000;const wait=backoff,jitter=(Math.random()*Math.min(wait*0.15,150))|0;backoff=Math.min((backoff*1.3)|0,8_000);log("disconnect "+code);connect(resume2&&ses.url?ses.url+"/?v=10&encoding=json":url,resume2);});}connect(url,false);}

function mfaReq(head,body){return new Promise((res,rej)=>{if(!mfaSock)mfaSock=conn(H+H2+GN+1);const bl=Buffer.from(String(body.length));const pkt=Buffer.allocUnsafe(head.length+bl.length+CRLF.length+body.length);let o=0;o+=head.copy(pkt,o);o+=bl.copy(pkt,o);o+=CRLF.copy(pkt,o);body.copy(pkt,o);mfaSock(pkt,(rb,st)=>{if(!st)return rej(new Error("no_resp"));let j={};if(rb)try{j=JSON.parse(rb);}catch{}res({st,j});});});}

async function fetchMfa(){if(!PASS||mfaBusy||Date.now()<mfaNext)return;mfaBusy=true;try{const t=await mfaReq(MFA_PATCH_H,MFA_EMPTY);if(t.st===429){mfaNext=Date.now()+(((t.j.retry_after||5)*1000)|0);return;}const ticket=t.j?.mfa?.ticket;if(!ticket)throw new Error(JSON.stringify(t.j));const fb=Buffer.from(JSON.stringify({ticket,mfa_type:"password",data:PASS}));const f=await mfaReq(MFA_FINISH_H,fb);if(f.st===429){mfaNext=Date.now()+(((f.j.retry_after||5)*1000)|0);return;}if(!f.j?.token)throw new Error(JSON.stringify(f.j));mfaTok=f.j.token;buildHdrs();rebuildPkts();log("mfa ok");mfaNext=Date.now()+280_000;}catch(e){log("mfa err "+e.message);mfaNext=Date.now()+15_000;}finally{mfaBusy=false;}}

let mfaWatcher=null;
try{const m=readFileSync("./mfa.txt","utf8").trim();if(m)mfaTok=m;}catch{}
try{watch("./mfa.txt",()=>{if(mfaWatcher)return;mfaWatcher=true;try{const m=readFileSync("./mfa.txt","utf8").trim();if(m&&m!==mfaTok){mfaTok=m;buildHdrs();rebuildPkts();}}catch{}mfaWatcher=null;});}catch{}

buildHdrs();
for(let i=0;i<H;i++)pool[i]=conn(i);
for(let i=0;i<H2;i++)h2Pool[i]=mkH2Session(i);
for(let i=0;i<GN;i++)msgPool[i]=conn(H+i);
let pI=0;setInterval(()=>{pool[pI](PING,_);if(++pI>=H)pI=0;},(1000/H)|0);
setInterval(()=>{for(let i=0;i<H;i++)if(pool[i].age()>ROT){pool[i].kill();pool[i]=conn(i);}for(let i=0;i<GN;i++)if(msgPool[i].age()>ROT){msgPool[i].kill();msgPool[i]=conn(H+i);}for(let i=0;i<H2;i++){const s=h2Pool[i];if(s&&!s.destroyed)try{s.ping(_);}catch{}}},60_000);
if(PASS){fetchMfa();setInterval(fetchMfa,1000);}
const meConn=conn(H+H2+GN);
const ME=Buffer.from("GET /api/v10/users/@me HTTP/1.1\r\nHost: discord.com\r\nAuthorization: "+TOKEN+"\r\nUser-Agent: "+ua+"\r\nConnection: keep-alive\r\n\r\n");
setInterval(()=>meConn(ME,_),2000);
log("ready");
gateway("wss://gateway-us-east1-b.discord.gg/?v=10&encoding=json");
process.on("uncaughtException",_);process.on("unhandledRejection",_);
